#!/usr/bin/env bash
repodir=$(pwd)
compiler="gfortran"
profile="debug"
src="${repodir}/src"
preproc="${repodir}/preproc"
interface="${repodir}/interface"
src_folders=("c_interface" "fortran_interface" "data_structure")
fypp_files=("submodule_attribute" "submodule_io" "submodule_variable")
fprettify_flags="-r -i 2 --strict-indent --disable-indent-mod"
fpm_flags="--compiler ${compiler} --profile ${profile}"

if [ -d "${src}" ]; then
  echo "Removing exsiting source directory..."
  rm -rf ${src}
fi

folders=$(find ${preproc} -type d)
for folder in ${folders}; do
  mkdir -p ${folder/preproc/src}
done

files=$(find ${preproc} -type f)
for file in ${files[@]}; do
  filename=$(basename -- "${file}")
  extension="${filename##*.}"
  filename="${filename%.*}"

  if [ ${extension} == "f90" ]; then
    echo "Copying ${filename}..."
    cp ${file} ${file/preproc/src}
  elif [ ${extension} == "fypp" ]; then
    echo "Preprocessing ${filename}..."
    chdir=${file/preproc/src}
    fypp ${file} ${chdir/fypp/f90}
  elif [ ${extension} == "py" ]; then
    echo "Generating C interface..."
    python ${file}
    mv module_c_interface.f90 ${src}/c_interface
  fi
done

echo "Source file generated successfully."
echo "Compile Fortran source code..."
if [ -d "./build" ]; then
  rm -rf ./build/
fi
fpm build ${fpm_flags}
echo "Running tests..."
fpm test ${fpm_flags}
