name = "netcdf_fortran"
version = "0.0.1"
maintainer = "htang2@alaska.edu"
author = "Han Tang"

#[preprocess]
#[preprocess.fypp]
#suffixes = 

[library]
source-dir = "src"

[build]
link = "netcdf"

[[test]]
name = "test"
source-dir = "test"
main = "test.f90"